### ISSUE TITLE
Remove permission from URI function

### ISSUE THREAD

**Issue by tricki** [gitawego/cordova-screenshot#125]
What is the reason that navigator.screenshot.URI() asks for the WRITE_EXTERNAL_STORAGE permission?

I'm not an Android expert but I just removed [the permission check](https://github.com/gitawego/cordova-screenshot/blob/master/src/android/Screenshot.java#L232-L236) and it still works, without asking the for run-time permission.

So, at least on my phone with Android 6.0.1 it works without requesting the permission. Is it different in other versions?

**Comment by mgrubinger** [comment]
@tricki This is now merged into the main branch.
@gitawego thanks for accepting the PR!
