### ISSUE TITLE
File path in iOS 7. 

### ISSUE THREAD

**Issue by MateenKadwaikar** [gitawego/cordova-screenshot#16]
Not able to see the screenshot which is taken in iOS 7. 

How can i fetch the pictures.

**Comment by jamesdouglasappleprint** [comment]
Exactly the same problem for me, readme doesn't seem to cover this

**Comment by gitawego** [comment]
could you tell me your ios version please ?

**Comment by jamesdouglasappleprint** [comment]
iOS 9 using

navigator.screenshot.save(function(error,res){
      if(error){
        console.error(error);
      }else{
        window.plugins.socialsharing.share('Message and image', null, 'file://'+res.filePath, null)
        console.log(res.filePath);
      }
    },'jpg',100,'myPet');

Android works fine, but iOS doesn't get the image when I pass it into a social-share plugin. The file saves to the iPhone, but the filePath i'm returned from the function doesn't work.

Any thoughts?

**Comment by MateenKadwaikar** [comment]
Able to get the filepath.
