### ISSUE TITLE
plugin not work with crosswalk. "org.crosswalk.engine.XwalkCordovaWebView can not be cast to ViewGroup"

### ISSUE THREAD

**Issue by danger1988** [gitawego/cordova-screenshot#43]
Hi, after update my ionic project from using native webview to crosswalk. The plugins can't not be built
(error on line 76 because the plugin can not detected my currently ionic is running on crosswalk).

I played around with the screenshot.java, replace the getBitmap function with this:
	private Bitmap getBitmap() {
		Bitmap bitmap = null;
		
		boolean isCrosswalk = true;
		TextureView textureView = findXWalkTextureView((ViewGroup)webView);
				bitmap = textureView.getBitmap();
		
		return bitmap;
	}

Now, the project can be built successfully. But when i capture a screen, an error raised:
"org.crosswalk.engine.XwalkCordovaWebView can not be cast to ViewGroup"

My crosswalk version is 13.41.318.0 , publish at 3-11-2015.

Please talk a look at this.

**Comment by gasperz** [comment]
Did you maybe solve this? I have similar problem. I have tested with cordova android (4.0.0) and latest cordova-plugin-crosswalk-webview. I only receive "Unfortunately, App has stopped."

before change my build got me this:
Screenshot.java:78: error: cannot find symbol
			View view = webView.getRootView();
			                   ^
  symbol:   method getRootView()
  location: variable webView of type CordovaWebView

Any idea how to fix this?

**Comment by danger1988** [comment]
Sorry gasperz,
I also have the same problem after i fixed the above problem. It seems that we can't get the view of the current webview when we are using cordova-plugin-crosswalk. We really need the author of this plugin find a new way to get the view instead of using webView.getRootView() when running on crosswalk

**Comment by gasperz** [comment]
Now that cordova is updated (to 5.0.0), default installation is not even working anymore. I get same error as before. I hope that someone with knowledge will get into this.

**Comment by gitawego** [comment]
I hope the latest update could resolve this problem, the plugin is now compatible with cordova-plugin-crosswalk-webview.
feedback is welcome :)

**Comment by gasperz** [comment]
Tested. It works for me. 

Thank you very much!
