### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [gitawego/cordova-screenshot#49]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by gitawego** [comment]
it is here: https://www.npmjs.com/package/com.darktalker.cordova.screenshot
thx for the info :)

**Comment by bau720123** [comment]
hi @gitawego 
My pleasure
