### ISSUE TITLE
publish github releases

### ISSUE THREAD

**Issue by viskin** [gitawego/cordova-screenshot#51]
Can you please start adding github releases starting with version 0.1.0?
It will make possible to upgrade/downgrade the plugin as needed. For example, I'm having issues with
Cordova 3.6.4 and Crosswalk compilation after getting the newest master. It's ok, but the issue is that I have no means to downgrade to previous version that worked, except maybe local backup. Release after each meaningful and tested update will make such problems less harmful.

**Comment by gitawego** [comment]
I've added tags, hope it works for you.

**Comment by viskin** [comment]
It's ok with v0.1.1 tag, thanks.
But v0.1.0 tag now points to version that both marked as 0.1.1 in plugin.xml, and supports Crosswalk.
Can you please update v0.1.0 tag to point at 8705f89 commit? This is latest version that seems like actual 0.1.0 without Crosswalk, exactly what I need.
Thank you.

**Comment by gitawego** [comment]
it's done.

you are welcome.

**Comment by viskin** [comment]
Great. Thanks!
