### ISSUE TITLE
wrong screenshot

### ISSUE THREAD

**Issue by nedoma** [gitawego/cordova-screenshot#64]
in Android platform I receive the black image. it worked perfect earlier.
Cordova version 5.0.0.
In ios everything is ok.

**Comment by tripodsan** [comment]
are you using crosswalk? if yes, see https://crosswalk-project.org/jira/browse/XWALK-2233

**Comment by nedoma** [comment]
yes. my app with crosswalk. addition of a line "<preference name="CrosswalkAnimatable" value="true" />" in config.xml solved my problem. thanks

**Comment by nedoma** [comment]
after addition of a line - pages where there are input fields - are frozen in data input attempt (((

**Comment by ArtiomSreda** [comment]
Not works. Image saved as blackscreen. 
CrosswalkAnimatable setting as TRUE, it does not solve the problem.
