### ISSUE TITLE
[chore] Please release a 0.1.4 to NPM

### ISSUE THREAD

**Issue by macdonst** [gitawego/cordova-screenshot#72]
Please tag and release 0.1.4 to NPM. The recent fix by @roblav96 is pretty crucial for those of us using cordova-ios 4.x.

**Comment by roblav96** [comment]
I must give all the credit to @afranc9 in this post here #68

**Comment by afranc9** [comment]
Thanks roblav96 i cant do the pull request before, but i hope the code work for you

**Comment by roblav96** [comment]
It works phenomenal! Thank you!

**Comment by zarko-tg** [comment]
Awaiting 0.1.5 over here :)

**Comment by gitawego** [comment]
@zarko-tg done
