### ISSUE TITLE
plugin fails silently

### ISSUE THREAD

**Issue by burtelli** [gitawego/cordova-screenshot#80]
In Android I'm calling the plugin exactly as in the examples. The plugin is definitely available (I checked in console), however it fails silently. Nothing is returned at all, not even an error message. 

Any ideas what might be causing this?

Cheers

PS: I've tried reinstalling. No change.

**Comment by thomasMary** [comment]
+1 got the same now, it was working perfectly before.

**Comment by burtelli** [comment]
Glad to hear it's not just me. 

My code works on iOS btw.

**Comment by gitawego** [comment]
could you please provide your cordova version, android platform version of cordova, and your android target version.

**Comment by burtelli** [comment]
Cordova 5.4.0
android-minSdkVersion (as defined in config.xml): 16
Actual Android version running on test device: 5.1.1

Please let me know if you require any other info. Thanks and keep up the great work!

**Comment by thomasMary** [comment]
cordova-android: 5.1.1
android-minSdkVersion=15
android-targetSdkVersion=22
Android version ( on device ): 6.0 and 5.1.1

**Comment by holmberd** [comment]
I'm experiencing the same problem with cordova-android: 5.1.1
Tried reverting the head back feb but no success.
Thanks.

**Comment by burtelli** [comment]
Hey gitawego, do you have any news or a timeline on this? Cheers

**Comment by holmberd** [comment]
Tried building it with Cordova 5.4.1 for Android 5.1.1 but no dice.

**Comment by bennerhq** [comment]
have the same issue (works perfect on iOS) - just updated to Cordova 6.1.0.... Any solution, please? ;)

**Comment by gitawego** [comment]
please use master version of cordova-plugin-crosswalk-webview if you wanna use this plugin in master and v0.1.5
because the crosswalk's feature ``onMessage`` is not yet available in npm.
please try this:
```
cordova plugin rm cordova-plugin-crosswalk-webview
cordova plugin add https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview
cordova clean
```
then try to build your project. it should resolve the problem.

**Comment by holmberd** [comment]
Got it running with v0.1.4 on Cordova and Android 5.1.1 with Crosswalk 1.4.0

**Comment by bennerhq** [comment]
perfect! brilliant! it' works! thanks a million! ;)

**Comment by burtelli** [comment]
Great, thanks for looking into it ! Will try that next week. Cheers

**Comment by ThinklabsGbR** [comment]
```
npm install -g cordova@5.4.1
cordova plugin add https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview
cordova plugin add https://github.com/gitawego/cordova-screenshot.git#v0.1.4
```

works for us

**Comment by burtelli** [comment]
yup, I can confirm this as well. Many thanks for your help!
