### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by DougiScotland** [gitawego/cordova-screenshot#81]
Hi

Compiling for Android with Monaca.io I get the following issue:

android/skeleton/platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:220: error: method does not override or implement a method from a supertype
    @Override
    ^

Bit of a newbie, so not sure how to fix it.  Any ideas would be welcome.

Thanks!

D

**Comment by farhax** [comment]
I also had this problem, it is caused on cordova-android v.4.1.1.
Bugg appeared in "Add support for Android 6 / API 23 runtime permissions"

app/platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:220: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by mjunaidsalaat** [comment]
+1
I'm experiencing the same error. Please provide any work around to fix this.

` :compileArmv7DebugJavaF:\workspace\BadgerPoint\platforms\android\src\com\darktal
ker\cordova\screenshot\Screenshot.java:220: error: method does not override or i
mplement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
 FAILED`

`BUILD FAILED`

`Total time: 1 mins 33.962 secs
Note: Recompile with -Xlint:deprecation for details.
1 error`

`FAILURE: Build failed with an exception.`

`What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
Compilation failed; see the compiler error output for details. `

Thanks

**Comment by gitawego** [comment]
could you please update to the latest version of cordova (6.0.0) and andorid platform (cordova-android@5.1.1) ? 
could you please tell me the android target defined in your config.xml as well ?

I can't reproduce this issue.

**Comment by mjunaidsalaat** [comment]
Thanks. @gitawego (Y)
Updating the cordova-platform @5.1.1 solved the problem for me.. :)

**Comment by bennerhq** [comment]
hello - i updated cordova to version 6.0.0 ... but i still get the below compiler error .. could you experts please help ? 

BR/Benner

------------

/Users/jbenner/Sites/rondon/platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:220: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:compileArmv7DebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.861 secs

/Users/jbenner/Sites/rondon/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/jbenner/Sites/rondon/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/jbenner/Sites/rondon/platforms

**Comment by gitawego** [comment]
have you tried ?
```
cordova platform update android
```

**Comment by bennerhq** [comment]
perfect - thanks a million!

**Comment by mjunaidsalaat** [comment]
@gitawego I guess we can close the issue now. :smile:

**Comment by DougiScotland** [comment]
Please could you leave it open a little longer?  I am in contact with tech support at Monaca.io to see how upgrading Cordova works with them and it may help others to post their response here.  Thanks.

**Comment by farhax** [comment]
@mjunaidsalaat actually don't close the issue.

I am still using android 4.1.1, (not possible to update, due to other issues).
Shouldn´t this be fixed for an older version?

**Comment by gitawego** [comment]
@farhax please stick with v0.1.5 for now. thx

**Comment by DougiScotland** [comment]
Thanks @gitawego - I just checked the version of Cordova currently being used in Monaca.io and it is 4.1.1.  Replacing the latest build of cordova-screenshot that was installed with v0.1.5 seems to have resolved the problem.  I hope this helps others with the same problem (especially @mjunaidsalaat) and thank you all for your contributions.
