### ISSUE TITLE
Android user do not want to see "Allow ____ to photos, media, and files on your device".

### ISSUE THREAD

**Issue by perry2of5** [gitawego/cordova-screenshot#94]
I am building an app for user's with-in our company. I use cordoba-screenshot to capture the app when user's submit feedback.  The app uses Crosswalk. I always use the "URI" method of capturing screenshots. I don't need access to the user's media or files. 

Is it possible to reconfigure the PERMISSIONS request to only ask for a screen shot of the current app when you call URI? I have a few senior staff very annoyed that our app asks for access to everything.

**Comment by perry2of5** [comment]
Here is the offending dialog. Android 6.0.1.

![screen shot 2016-09-02 at 4 12 59 pm](https://cloud.githubusercontent.com/assets/181138/18220563/2cef4cb6-7128-11e6-9861-8e63e9a1d199.png)

Also, I'm happy to hack down this plugin to the subset I need if it is going to be possible to avoid this dialog. 

BTW: The plugin is very handy. Thanks for maintaining it.

**Comment by perry2of5** [comment]
I created a fork of this project to support my needs. https://github.com/perry2of5/cordova-screenshot/issues/94 It only supports Crosswalk on Android and the default web view on iOS. It does not request any permissions from the OS. The plugin is not as full-featured as this one, but my users are happy now. Thanks for maintaining this plugin -- I couldn't have created the forked plugin from scratch without a much larger investment of time. Cheers! Tim

**Comment by wilfredonoyola** [comment]
@perry2of5 Thanks for this. I implemented this and so far it works!
